### ISSUE TITLE
Bug? Or am I dumb

### ISSUE THREAD

**Issue by HamBurgerHam** [Sharlottes/sharustry#3]
I might just be dumb but whenever I tried to shoot the Balkan it just crash the game (or is it supposed to be a test weapon) probably my device just couldn't handle it

**Comment by HamBurgerHam** [comment]
Opps

**Comment by MEEPofFaith** [comment]
Crash Report?
![modding](https://user-images.githubusercontent.com/54301439/112899880-9178b300-9097-11eb-8b34-d9e65a421697.png)

**Comment by HamBurgerHam** [comment]
So I'm dumb?

**Comment by MEEPofFaith** [comment]
How am I supposed to know anything about why an issue is occurring with absolutely no info.

**Comment by HamBurgerHam** [comment]
Wait I need to give info? Shit I don't know coding

**Comment by MEEPofFaith** [comment]
What type of device are you on? (Computer, Android, iOSuck)

**Comment by HamBurgerHam** [comment]
Android 9 - Redmi note 5

**Comment by HamBurgerHam** [comment]
ISSUES CLOSED FOR SOME REASON IT WORKS NOW AFTER REINSTALLING
