### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by QmelZ** [Sharlottes/sharustry#4]
mod version: 0.1.2.2

game version: 126.2

[crash log](https://github.com/Sharlottes/sharustry/files/6228623/crash-report-03_30_2021_14_21_25.txt)

crashes on game launch

**Comment by sk7725** [comment]
https://github.com/Sharlottes/sharustry/commit/35ce35f2e72af5936601ee874c0ff7a3dbaa8165#diff-e2263f5a0ed96f335ec67ab3a06ded04c02429c5a199f4f86b78513464ba23e2
