### ISSUE TITLE
Mono Breaking Bug

### ISSUE THREAD

**Issue by MrDuck557** [Sharlottes/sharustry#9]
itemDrop (logic) doesn't work, and monos don't recognize the core. In addition, manually trying to drop items into the core doesn't work. (this was with armedFoundation)

**Comment by MrDuck557** [comment]
Further testing with the armed nucleus shows that the turrets are interfering since you can drop graphite into the armed nucleus.

**Comment by Sharlottes** [comment]
fixed core bug. fixing unit bug now https://github.com/Sharlottes/sharustry/commit/40405eb417e07a1c186025d6a341588fc564748f

**Comment by Sharlottes** [comment]
ohno save file is got bugged wait a min

**Comment by Sharlottes** [comment]
fixed.
